# Generated by Django 4.2.4 on 2023-10-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название, которое будет отображено пользователям', max_length=100, verbose_name='Название пункта')),
                ('code_name', models.CharField(help_text='По этому названию будет вызываться меню в коде', max_length=50, verbose_name='Кодовое название пункта')),
                ('url', models.CharField(max_length=250, verbose_name='Ссылка, куда будет вести пункт меню')),
                ('position', models.IntegerField(verbose_name='Позиция в меню')),
                ('parent', models.ForeignKey(help_text='Текущий пункт будет подпунктом выбранного родительского пункта', on_delete=django.db.models.deletion.DO_NOTHING, to='menus.menuitem', verbose_name='Выберите родительский пункт меню')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
    ]
