# Generated by Django 4.2.4 on 2023-10-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menuitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Текущий пункт будет подпунктом выбранного родительского пункта', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menus.menuitem', verbose_name='Выберите родительский пункт меню'),
        ),
    ]
