# Generated by Django 4.2.4 on 2023-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_alter_menuitem_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='parent',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ManyToManyField(blank=True, help_text='Текущий пункт будет подпунктом выбранного родительского пункта', null=True, to='menus.menuitem', verbose_name='Выберите родительский пункт меню'),
        ),
    ]
