# Generated by Django 4.2.4 on 2023-10-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_alter_menuitem_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.URLField(verbose_name='Ссылка, куда будет вести пункт меню'),
        ),
    ]
