# Generated by Django 4.2.4 on 2023-10-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_alter_menuitem_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=250, verbose_name='Ссылка, куда будет вести пункт меню'),
        ),
    ]
