# Generated by Django 4.2.4 on 2023-10-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0009_remove_menuitem_code_name_remove_menuitem_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createmenu',
            options={'verbose_name': 'Создание меню', 'verbose_name_plural': 'Создание меню'},
        ),
    ]
