# Generated by Django 4.2.4 on 2023-10-29 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_alter_createmenu_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createmenu',
            options={'verbose_name': 'Менюшка', 'verbose_name_plural': 'Менюшки'},
        ),
    ]
