# Generated by Django 4.2.4 on 2023-10-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0011_alter_createmenu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='children',
            field=models.ManyToManyField(blank=True, to='menus.menuitem', verbose_name='Выберите пункты данного меню'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='code_name',
            field=models.CharField(blank=True, help_text='По этому названию будет вызываться меню в коде. Необязательное поле', max_length=50, verbose_name='Кодовое название подменю'),
        ),
        migrations.DeleteModel(
            name='CreateMenu',
        ),
    ]
