# Generated by Django 4.2.4 on 2023-10-29 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0013_alter_menuitem_children_alter_menuitem_code_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='children',
            new_name='childs',
        ),
    ]
