# Generated by Django 4.2.4 on 2023-10-29 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0014_rename_children_menuitem_childs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='childs',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menus.menuitem', verbose_name='Родительский пункт меню'),
        ),
    ]
